import oracledb
import logging
from config import Config

# Configure logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

_pool = None

def get_pool():
    global _pool
    if _pool is None:
        try:
            # Enable thin mode connection pooling
            _pool = oracledb.create_pool(
                user=Config.DB_USER,
                password=Config.DB_PASSWORD,
                dsn=Config.DB_DSN,
                min=2,
                max=10,
                increment=1
            )
            logger.info("Oracle Database connection pool created successfully.")
        except Exception as e:
            logger.error(f"Failed to create Oracle connection pool: {e}")
            raise e
    return _pool

def get_connection():
    return get_pool().acquire()

def execute_query(query, params=None, commit=False):
    """
    Execute a parameterized query and return the cursor or results.
    """
    conn = get_connection()
    cursor = conn.cursor()
    try:
        if params:
            cursor.execute(query, params)
        else:
            cursor.execute(query)
        
        if commit:
            conn.commit()
            
        return cursor, conn
    except Exception as e:
        if commit:
            conn.rollback()
        cursor.close()
        conn.close()
        raise e

def execute_fetch_all(query, params=None):
    """
    Execute a query and fetch all results as a list of dicts.
    """
    cursor = None
    conn = None
    try:
        cursor, conn = execute_query(query, params)
        columns = [col[0].lower() for col in cursor.description]
        results = [dict(zip(columns, row)) for row in cursor.fetchall()]
        return results
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def execute_fetch_one(query, params=None):
    """
    Execute a query and fetch the first result as a dict.
    """
    cursor = None
    conn = None
    try:
        cursor, conn = execute_query(query, params)
        columns = [col[0].lower() for col in cursor.description]
        row = cursor.fetchone()
        if row:
            return dict(zip(columns, row))
        return None
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

def init_db():
    """
    Creates tables if they do not exist using PL/SQL dynamic blocks.
    """
    # PL/SQL blocks for safe dynamic creation
    ddl_blocks = [
        # CUSTOMERS
        """
        DECLARE
            cnt NUMBER;
        BEGIN
            SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'CUSTOMERS';
            IF cnt = 0 THEN
                EXECUTE IMMEDIATE 'CREATE TABLE customers (
                    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(100) NOT NULL,
                    mobile VARCHAR2(15) NOT NULL UNIQUE,
                    address VARCHAR2(1000),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
                EXECUTE IMMEDIATE 'CREATE INDEX idx_cust_mobile ON customers(mobile)';
            END IF;
        END;
        """,
        
        # VEHICLES
        """
        DECLARE
            cnt NUMBER;
        BEGIN
            SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'VEHICLES';
            IF cnt = 0 THEN
                EXECUTE IMMEDIATE 'CREATE TABLE vehicles (
                    vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id NUMBER NOT NULL,
                    vehicle_number VARCHAR2(20) NOT NULL UNIQUE,
                    make VARCHAR2(50),
                    model VARCHAR2(50),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_vehicle_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE
                )';
                EXECUTE IMMEDIATE 'CREATE INDEX idx_veh_number ON vehicles(vehicle_number)';
            END IF;
        END;
        """,
        
        # BILLS
        """
        DECLARE
            cnt NUMBER;
        BEGIN
            SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'BILLS';
            IF cnt = 0 THEN
                EXECUTE IMMEDIATE 'CREATE TABLE bills (
                    bill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bill_number VARCHAR2(20) NOT NULL UNIQUE,
                    customer_id NUMBER NOT NULL,
                    vehicle_id NUMBER NOT NULL,
                    bill_date DATE NOT NULL,
                    km NUMBER NOT NULL,
                    subtotal NUMBER(10, 2) NOT NULL,
                    discount NUMBER(10, 2) DEFAULT 0.00,
                    tax NUMBER(10, 2) DEFAULT 0.00,
                    total NUMBER(10, 2) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_bill_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
                    CONSTRAINT fk_bill_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)
                )';
                EXECUTE IMMEDIATE 'CREATE INDEX idx_bill_number ON bills(bill_number)';
                EXECUTE IMMEDIATE 'CREATE INDEX idx_bill_date ON bills(bill_date)';
            END IF;
        END;
        """,
        
        # BILL_ITEMS
        """
        DECLARE
            cnt NUMBER;
        BEGIN
            SELECT count(*) INTO cnt FROM user_tables WHERE table_name = 'BILL_ITEMS';
            IF cnt = 0 THEN
                EXECUTE IMMEDIATE 'CREATE TABLE bill_items (
                    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bill_id NUMBER NOT NULL,
                    description VARCHAR2(255) NOT NULL,
                    amount NUMBER(10, 2) NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_item_bill FOREIGN KEY (bill_id) REFERENCES bills(bill_id) ON DELETE CASCADE
                )';
            END IF;
        END;
        """
    ]
    
    conn = get_connection()
    cursor = conn.cursor()
    try:
        for block in ddl_blocks:
            cursor.execute(block)
        conn.commit()
        logger.info("Database schema initialized successfully.")
    except Exception as e:
        conn.rollback()
        logger.error(f"Failed to initialize database: {e}")
        raise e
    finally:
        cursor.close()
        conn.close()
